[project]
name = "daims-map-analysis"
version = "0.1.0"
description = "Analysis and processing for DAIMS Giant's Causeway map"
authors = ["Maeve Murphy Quinlan"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[dependencies]
python = ">=3.11"
jupyter = "*"
pandas = "*"
bibtexparser = ">=1.4.4,<2"
openpyxl = ">=3.1.5,<4"
pillow = ">=12.3.0,<13"
